=head1 NAME

pmps.pl - IP Phone multicast provisioning server

=head1 SYNOPSIS

./pmps.pl [options]

=head1 OPTIONS

=over 4

=item B<-h help>
Print the manual page and exits.

=item B<-v verbose>
Increase the level of verboseness on the console.

=item B<-i interface>
Set multicast lstener interface.

=item B<-s server>
http server name or ip address for URL.

=item B<-u url>
Set configuration URL for NOTIFY packet

=back

=head1 DESCRIPTION

This server listen multicast address 224.0.1.75,
parse SUBSCRIBE packages and send send NOTIFY
with configuration URL to phones.

Default provisionoing URL:
http://$srv/pmps/?pmps=$pmpsip&hw=$mod&fw=$ver&mac=$mac&ip=$ip

can be changed by option -url

All values in URL rewritten by special paramethers:

=over 4

=item B<srv>
http server name or address. By default - server interface ip address.

=back

Next variables get values from SUBSCRIBE packet and may be used in URL:

=over 4

=item B<ven>
phone vendor

=item B<mod>
Model of SIP phone

=item B<ver>
Firmware revision

=item B<mac>
Phone mac address

=item B<ip>
Phone ip address

=item B<lip>
Phone local ip address

=item B<to, from, cid, via, cseq>
NOTIFY message header fields

=back

=cut
